[package]
name = "moonless"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
logs = "0.7.1"
lz-str = "0.2.1"
